### ISSUE TITLE
error doing "code-insiders ." command "command not found"

### ISSUE THREAD

**Issue by Vesloo** [CodedotAl/code-clippy-vscode#11]
Hello, I was trying to install this vscode extension but I have this error, anyone can help me ?
I didn't understood how to add the extension to vscode - insiders to make it work
When I open the repository on vscode - insiders and click on "run extension" I get this error: ![Capture d’écran 2022-06-22 à 11 11 32](https://user-images.githubusercontent.com/40546525/174991447-a90f2416-3a0e-4380-a432-aeb1fd8b48b5.png)
And when I'm writing my api key in package.json and running extension I get this error: 
Activating extension 'ncoop57.code-clippy' failed: vscode.window.getInlineCompletionItemController is not a function.
And this when i'm writing in a document when the extension run:
Error: Model flax-community/gpt-neo-125M-code-clippy-dedup-2048 is currently loading

**Comment by ncoop57** [comment]
We no longer require code-insiders, so I am going to go ahead and mark this issue as resolved. Please let me know if you still have issues using this in normal vscode.
