### ISSUE TITLE
Cannot start the program with F5

### ISSUE THREAD

**Issue by wlwatkins** [CodedotAl/code-clippy-vscode#12]
Hi, 
I just installed vscode insiders for windows and cloned the repo. When opening it as hitting F5 here's what I am getting

```
src/extension.ts:67:7 - error TS2345: Argument of type '{ text: string; range: vscode.Range; trackingId: string; }' is not assignable to parameter of type 'CustomInlineCompletionItem'.
  Object literal may only specify known properties, and 'text' does not exist in type 'CustomInlineCompletionItem'.

67       text: rs.completions[i],
         ~~~~~~~~~~~~~~~~~~~~~~~

[10:25:11] Found 1 error. Watching for file changes.
```

Not knowing nodejs, i have no clue where to start

**Comment by hgouveia** [comment]
@willmendil i had the same issue and fixed by replacing ` text: rs.completions[i] ` to `insertText: rs.completions[i]` it seems the latest vscode insider change the parameters signature of `CustomInlineCompletionItem`

**Comment by wlwatkins** [comment]
ok tis worked but not fully now i get these in the new window

![image](https://user-images.githubusercontent.com/8661949/175278881-2f542467-6fe4-4735-a5a7-9cd28eda55a1.png)

**Comment by Vesloo** [comment]
Got the same issue

**Comment by hgouveia** [comment]
@willmendil @Vesloo  yeap me too, it seems this repository hasn't been updated for a while and is using old calls to vscode extension api,, i added `--enabled-proposed-api` into the .vscode/launch.json arguments, but it doesnt work

**Comment by wlwatkins** [comment]
Well, I guess with github's move to make copilot a pay for product, this repo might get some attention. I'm trying tabnine with mixed results. But I'd really like to participate with an open source solution, if only by sending telemetry. (I don't have the skills, nor time to do the coding). Maybe copilot was just a happy story, but now i'm back to the old ways...

**Comment by SaumyaBhandari** [comment]
I got the exact same error while a new insider window is being opeaned.

**Comment by SaumyaBhandari** [comment]
Suggestions by the software does not work. So I checked the code-clippy's window while waiting for the code to generate, I saw this: 

![image](https://user-images.githubusercontent.com/60599110/175531542-4a664bc0-d8f9-4182-9757-6b9a79662232.png)

The suggestion array was generated as empty. The model's suggesting empty values

**Comment by SohamMalakar** [comment]
It's giving me the exact same issue. I've tried normal/insiders both. It didn't work for either of them.

**Comment by MHuiG** [comment]
I'm not sure if this repository is still being maintained, try this : https://github.com/CodedotAl/code-clippy-vscode/pull/13/files

**Comment by SohamMalakar** [comment]
> I'm not sure if this repository is still being maintained, try this : https://github.com/CodedotAl/code-clippy-vscode/pull/13/files

@MHuiG I've cloned the repo and started the extension. I was able to open the debug mode without any errors. But while writing a code, it was giving me some errors. But it was giving me some suggestions too.

These are the error messages:
`error: 'Model flax-community/gpt-neo-125M-code-clippy-dedup-2048 is currently loading'`
`error: 'Rate limit reached. Please log in or use your apiToken'`

Here is the full **DEBUG CONSOLE** output:
```
capabilities resolved immediately
assistant is closing
capabilities resolved immediately
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Model flax-community/gpt-neo-125M-code-clippy-dedup-2048 is currently loading', estimated_time: 21.041305541992188}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(3) ['impl OpenOption for Option {
fn parse_open_options', '// ===================================================================

fn main() {
  
}
', '// IFC2 calls the following method:
//
//']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(3) ['}
}

//
//WKwidgets', 'fn parse_open_options_with_options() {
', 'f:f
}

fn parse_open_options']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(3) ['//
// Copyright 2014-2020 The Kubernetes Authors.
//', '//
//
//
//
//
//
//
//', '//
// Copyright 2019 The Kubernetes Authors. All rights reserved.']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(3) ['}

fn main() {

::_f', '// This call is taken from the compiler and passed to the library
//', 'extern "C" {
	fn main(argc, arg']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(3) ['void:
::1.5.5.1 :
', 'f f
:f
:f
:f
:f
:', 'class:
:class:
']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(3) ['fn main_with_c() {
// I don't', '// Use a test for testing the behavior.
//
// Usage:', 'describe "Powar_S3_Dwip/P']
(3) ['// Read the first byte of the string
', 'if (strlen(tagname) == 0) {', 'bool is_thread_safe = false;
']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(2) ['write_data(write_data_info, write_data', 'ichar_unittest() {
	ichar_unittest']
assistant is closing
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(2) ['write_data(write_data_info, write_data', 'ichar_unittest() {
	ichar_unittest']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(3) ['{
// I'm doing the following so that when I call
', '{
	print!("\n");
	print!("{:', '{
for f in os::file_operations().to_']
(3) ['// use std::io::
//', 'impl <1> <2> File::WriteFile for <2', 'fn main()
{

}']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(3) ['// I think I understand what I'm doing wrong but I'm not', '#include <stdio.h>

// #include <', '//
//
//
//
//
//
//
']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(3) ['}

#include "clang_core/clang_assert', '#[test_func_Mangle_1_Mangle_', 'use std::io::unittest;
use std::ruby']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(3) ['fn main()
{
  assert_eq!(', 'fn main()
{
 ::testing::random_un', '// This is a program to give you
// a list of the']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(1) ['() {
self.write_file("']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
(1) ['{
let mut output = _;
_ =']
(3) ['fn test_std::io::Write(in: &std::', 'fn main_do_stuff() {
if!!', '#: src/main/index.js:20
#:']
(3) ['{
write_one_file("c:/users/user1', '{
if!(::_std::is_io_fn', '{
let mut i = 0;
']
(3) ['fn main_func() {
	fmt!("fmt', 'let mut reader = ::Reader;
let mut obj = ::Obj', 'fn main()
{} 

// Return the address of']
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
{error: 'Rate limit reached. Please log in or use your apiToken'}
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
{error: 'Rate limit reached. Please log in or use your apiToken'}
{error: 'Rate limit reached. Please log in or use your apiToken'}
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
flax-community/gpt-neo-125M-code-clippy-dedup-2048
flax-community/gpt-neo-125M-code-clippy-dedup-2048
{error: 'Rate limit reached. Please log in or use your apiToken'}
{error: 'Rate limit reached. Please log in or use your apiToken'}
{error: 'Rate limit reached. Please log in or use your apiToken'}
{error: 'Rate limit reached. Please log in or use your apiToken'}
```

**Comment by MHuiG** [comment]
@SohamMalakar This is over the rate limit because it uses the Huggingface account's API.

Even with the Huggingface account's API token, there are limitations and a Pro plan is required.

This limitation can only be removed if the model is deployed locally or on your own server without using the Huggingface account's API.

However, local deployment consumes local resources, And the VSC plug-in requires a local version to be refactored.

**Comment by MHuiG** [comment]
If you want to get rid of the Huggingface account's API, I think the first thing to do is to encapsulate gpt-code-clippy as a service (code clippy as service) like [clip-as-service](https://github.com/jina-ai/clip-as-service) , and then refactor the  vsc plug-in here to use the service encapsulated above. 

There's still a long way to go, and the repo hasn't been updated in half a year.

**Comment by SohamMalakar** [comment]
@MHuiG Thanks for the information. 😄

**Comment by SohamMalakar** [comment]
The actual/parent version of the [copilot-clone](https://github.com/hieunc229/copilot-clone) works for me.

**Comment by ncoop57** [comment]
Hi y'all thanks for the active discussions. We are hoping to start back up maintenance of this repository in the next few weeks and will look to incorporate some of the ideas y'all have put here. PRs are welcome!

**Comment by ncoop57** [comment]
Is anyone here interested in helping with refactoring the code to work similar to @MHuiG's suggestion for "code clippy as a service"? I think wrapping up HF models similar to this repo: https://github.com/moyix/fauxpilot where you can locally or remotely create a docker container that hosts a optimized version of the model for deployment and point this extension to it is a good evolution for this repository.
