### ISSUE TITLE
npm run vscode:prepublish Found 1 error in src/extension.ts:67 Argument of type '{ text: string; range: vscode.Range; trackingId: string; }' is not assignable to parameter of type 'CustomInlineCompletionItem'.

### ISSUE THREAD

**Issue by Kuchiriel** [CodedotAl/code-clippy-vscode#18]
src/extension.ts:67:7 - error TS2345: Argument of type '{ text: string; range: vscode.Range; trackingId: string; }' is not assignable to parameter of type 'CustomInlineCompletionItem'.
  Object literal may only specify known properties, and 'text' does not exist in type 'CustomInlineCompletionItem'.

67       text: rs.completions[i],
         ~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/extension.ts:67

**Comment by MLSci** [comment]
STR:
1. type `code .` to open VSCode
2.  press F5.

Symptom:
An error dialog shows `Error exists after running preLaunchTask 'npm: watch'.`

Detailed error:
```
[{
	"resource": "/c:/Users/User/Documents/code-clippy-vscode/src/extension.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type '{ text: string; range: vscode.Range; trackingId: string; }' is not assignable to parameter of type 'CustomInlineCompletionItem'.",
	"source": "ts",
	"startLineNumber": 67,
	"startColumn": 7,
	"endLineNumber": 67,
	"endColumn": 7
}]
```

**Comment by ncoop57** [comment]
Hi y'all, could you please include your VSCode Insider version and OS?

**Comment by MLSci** [comment]
VSCode ver: 1.70.2
OS: Windows 11 x64

Question: must we use the insider ver instead of the stable release of vscode?

**Comment by ncoop57** [comment]
@MLSci yes, for the current version, you must use insider. In the next couple weeks, we hope to move to the normal vscode version and make installation easier.

**Comment by arcticoder** [comment]
I get the same error with `vsce package`
 
 ```
 src/extension.ts:67:7 - error TS2345: Argument of type '{ text: string; range: vscode.Range; trackingId: string; }' is not assignable to parameter of type 'CustomInlineCompletionItem'.
  Object literal may only specify known properties, and 'text' does not exist in type 'CustomInlineCompletionItem'.
  ```

```
PS> vsce --version
2.10.2
```
