### ISSUE TITLE
Read or Write token?

### ISSUE THREAD

**Issue by LynxHasGithub** [CodedotAl/code-clippy-vscode#2]
in the website i get read and write options which one do i use

**Comment by ncoop57** [comment]
Hi @FyxedHasGithub! Could you be a bit more specific on which website and which step you are trying to accomplish?

**Comment by MaxGurbanli** [comment]
He means whether to choose "read" or "write" when creating a token on HuggingFace

**Comment by ncoop57** [comment]
From what I remember it should only require read access @FyxedHasGithub

**Comment by ncoop57** [comment]
Gonna close this for now, if you continue to have issues about this, please feel free to reopen!
