### ISSUE TITLE
API error, extension won't start

### ISSUE THREAD

**Issue by NicolaSpadari** [CodedotAl/code-clippy-vscode#24]
I'm trying to enable the extension by compiling it as reported in the readme, the code compiles with the command `npm run esbuild` and the extension gets generated correctly with `vsce package`.

I make sure to have the correct api key in the configuration, but the extension throws this error at startup:

>editor/inlineCompletions/actions is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["inlineCompletionsAdditions"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api ncoop57.code-clippy

Looks like that `inlineCompletionsAdditions` is the API to be used instead of `inlineCompletions` in `package.json`, but even with that and after adding `--enable-proposed-api ncoop57.code-clippy` in `.vscode/launch.json`, the error still persists.

Any idea why? Running VSCode 1.71.0, (not insider as it's not required anymore), node 17.6.0, npm 8.5.1

**Comment by ncoop57** [comment]
Hi @NicolaSpadari I received that error as well, but the extension still worked. I am unsure why that error pops up as I also made sure to enable the API. Could you test some autocompletions to see if the extension works even with that error?

**Comment by NicolaSpadari** [comment]
Looks like it's trying to give suggestions, but after ~10 minutes it still shows "Error: Model flax-community/gpt-neo-125M-code-clippy-dedup-2048 is currently loading"

Maybe it's something on my end but yes, even with that error the extension appears to be functioning

**Comment by ncoop57** [comment]
Hmmm 🤔 it should not take that long to load the model. We will be moving away from huggingface's inference API soon so anyone can host their own model so that loading problem won't occur any more
