### ISSUE TITLE
QUESTION: is it possible to use BLOOM model?

### ISSUE THREAD

**Issue by Celestialme** [CodedotAl/code-clippy-vscode#30]
is it possible to use BLOOM model to finetune for specifically code generation?
maybe data should look like that
prompt:
sumTwoNumbers
target:
function sumTwoNumbers(a,b){
return a+b
}

so prompts to be function names and targets be whole function? so when we start typing function name it can generate function body?
I don't  have enough experience in AI it's just an idea, because I have tested bloom model and is almost perfect for this task out of the box.

**Comment by ncoop57** [comment]
Yes, you can use the bloom model. This section of the README discusses how to change the model to whatever one you want: https://github.com/CodedotAl/code-clippy-vscode#2-using-code-clippy
