### ISSUE TITLE
downloading "vscode.proposed.inlineCompletions.d.ts" and "vscode.d.ts"

### ISSUE THREAD

**Issue by elttaes** [CodedotAl/code-clippy-vscode#32]
My network is not very good. When npm install, I will get stuck when downloading these two ts files. Can I skip this process of downloading ".ts"? Because I saw that these two files are already in the folder, I don't understand why npm still trying to download these two files.

**Comment by wvhulle** [comment]
How did you solve it?

**Comment by elttaes** [comment]
> How did you solve it?

I don’t know how to solve it. I use copilot now.
