### ISSUE TITLE
Error: Authorization header is correct, but the token seems invalid

### ISSUE THREAD

**Issue by kgeorgiou-cognity** [CodedotAl/code-clippy-vscode#33]
I have followed the steps of the instructions and I'm getting the error
```Error: Authorization header is correct, but the token seems invalid```
and 
```[ncoop57.code-clippy]: editor/inlineCompletions/actions is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["inlineCompletionsAdditions"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api ncoop57.code-clippy```

I generated a new access token from huggingface and pasted it in an empty text document, but it doesn't seem to work.

**Comment by chrisk8er** [comment]
hi... @kgeorgiou-cognity  how do you fix this issue?

**Comment by ncoop57** [comment]
@chrisk8er are you getting a similar issue?
