### ISSUE TITLE
Just tried installing code-clippy and getting error

### ISSUE THREAD

**Issue by KrakenBadger** [CodedotAl/code-clippy-vscode#7]
Hello, I just tried to install code-clippy as I was interested in trying out the code completion.  I cloned your extension and ran npm install on it.  However when I ran the extension using f5 in vscode, according to your instructions, I encountered the following error.

I tried doing this on windows and in wsl running debian.  I got the same error both times.

![image](https://user-images.githubusercontent.com/76974782/148157830-0ed34f89-e667-4678-90c5-c404662e4785.png)

**Comment by ncoop57** [comment]
Hi there @ami6828 just need a bit more info. Are you currently using the vscode insiders edition when trying to run the extension?

**Comment by KrisCowie** [comment]
I think I've got the same error, also running Windows
I am running Visual Studio Code - Insiders though (side note, thank you so much for making this, pretty incredible!)

Just an update, seems like the same problem exists on Mac as well (just tried with my MacBook)

![image](https://user-images.githubusercontent.com/67929224/148462378-383f4303-adec-4c4d-b127-b148af729f71.png)

**Comment by ncoop57** [comment]
@KrisCowie you seem to be using an older version of code-clippy-vscode. (you have a demo.gif file that has now been changed to code-clippy-demo.gif). Could you please try and fresh clone and see if the error goes away? @ami6828 this might be a similar reason for your error.

When using the new version, please make sure to clone it from this repo, not my personal fork (it is very outdated compared to the one here).

**Comment by KrisCowie** [comment]
@ncoop57 It works now, awesome!
Thanks, sorry I was following the installation instructions a little too closely haha, should've realized it wasn't the same as the repo I was looking at:
```
git clone https://github.com/ncoop57/code-clippy-vscode
cd code-clippy-vscode
npm install
code-insiders .
```
Thanks!

Ah it's a little finicky, just have to get the wording right. Neato!
![image](https://user-images.githubusercontent.com/67929224/148569540-acad04f6-e0ac-4853-a057-fc88c883fb17.png)


![image](https://user-images.githubusercontent.com/67929224/148570185-700bd5b7-0c6a-42bf-85d4-d872909b7dad.png)

Ohh and you can change the model! Just figured that out. Alright, everything looks good, thanks again Nathan!

**Comment by ncoop57** [comment]
🤦 thank you @KrisCowie for pointing out the incorrect installation instructions. no wonder people have been having issues :rofl:. Glad it is working for you now!

**Comment by ncoop57** [comment]
Gonna close this for now @ami6828. Feel free to reopen if still experiencing issues
