### ISSUE TITLE
Getting errors trying to put HuggingFace API

### ISSUE THREAD

**Issue by maxfyjj** [CodedotAl/code-clippy-vscode#8]
Hi! I'm sorry, but i can't put the HuggingFace API; I get this: 
![image](https://user-images.githubusercontent.com/74956863/148803812-d5d94713-e851-4a5d-b779-fc6524029521.png)

I'm sure that i'm putting the api without spaces, or modifying it. I got this api doing "New Token", putting a random name (Clippy Code) and copying the generated text.

![image](https://user-images.githubusercontent.com/74956863/148804024-192c425d-6edd-4239-b8cc-e73f822359dd.png)

**Comment by ncoop57** [comment]
@MaxPlay066 could you try making the token write access? I'm wondering if additional permissions are required

**Comment by maxfyjj** [comment]
> @MaxPlay066 could you try making the token write access? I'm wondering if additional permissions are required

Already tried. It doesn't work

**Comment by ncoop57** [comment]
@MaxPlay066 apologies for such a late reply. I figured out the issue. HuggingFace made a change to their site in what they call access tokens and API tokens. The token you have there is a user access token, but they have a separate system for API tokens that is needed for this VSCode extension. Here is the link to get to your API token: https://api-inference.huggingface.co/dashboard/api_token

**Comment by ncoop57** [comment]
Gonna close this now, but feel free to reopen it if the issue persists
