### ISSUE TITLE
Getting an unknown error on extension window

### ISSUE THREAD

**Issue by JoshJarabek7** [CodedotAl/code-clippy-vscode#9]
![Screen Shot 2022-02-18 at 2 30 45 AM](https://user-images.githubusercontent.com/84693614/154646555-c2e5a48a-8ffa-4663-b7c0-831ffc408093.png)

Opens up the extension window. I start typing and I get this "Error: Unknown error" without any details.

**Comment by ncoop57** [comment]
Interesting 🤔  could you share some more info on your environment please? OS, VScode version, model you are using to do the generation, etc? Also, have you made sure to add your API token?

**Comment by JoshJarabek7** [comment]
MacOS 12.2, M1 chip, VS Code Insider Version: 1.65.0-insider (Universal)

I haven't been able to do the generation yet. The error comes when it opens an extension window when I run the debugger. I start typing and about 5-10 seconds into it the error pops up. I haven't been able to add the API token yet because there's nothing popping up to enter my API token into it.

**Comment by ncoop57** [comment]
@JoshJarabek7 you should still be able to add the token by going to your vacode settings in the window that pops up when you launch the debugger. You can search for clippy to find where you can put the key. 

If that doesn't work, it might be a difference in vscode insiders version. Maybe the API for showing autocompletion hints changed. I will check what version works for me tomorrow or Monday.

**Comment by RoelStierum** [comment]
I am also experiencing this issue, i am running windows 10 and i'm also running vscode insider 1.65.0

**Comment by ncoop57** [comment]
Just tested the extension on vscode insider 1.65.0 and it worked, so that isn't the issue 😔. @RoelStierum @JoshJarabek7 do you have any other vscode extensions installed in the vscode insider that might be conflicting with this extension?

**Comment by JoshJarabek7** [comment]
Ah, that was the problem. Sorry about that. It works now.

**Comment by ncoop57** [comment]
> Ah, that was the problem. Sorry about that. It works now.

Awesome! And no worries, do you mind sharing which extension conflicted? Might be useful for others to know
